server:
  port: 8080

spring:
  application:
    name: system
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:192.168.150.128}:${MYSQL_PORT:3306}/booking_system?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:111111}
  data:
    redis:
      host: ${REDIS_HOST:192.168.150.128}
      port: ${REDIS_PORT:6379}
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s

  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY:sk-7b133a6daf9a462cbec22ff40a62c506}
      chat:
        options:
          model: qwen-plus
    vectorstore:
      redis:
        initialize-schema: true
        index-name: ai-index
        prefix: "embedding:"
    # mcp:
    #   client:
    #     stdio:
    #       servers-configuration: classpath:baiduMap.json

booking:
  ai:
    session:
      title: Hello，我是预约AI助理
      describe: 我是你贴心的智能助理，我不仅能推荐场馆、预约场馆，还能为您畅聊心事。
      examples:
        - title: "场馆推荐"
          describe: "能帮我推荐一个合适的场馆吗？"
        - title: "查询我的预约"
          describe: "最近有什么新的预约吗？"
        - title: "ai预约"
          describe: "能帮我预约一个场馆吗？"
    prompt:
      system: user.txt
      route-agent: route-agent-system-message.txt
      recommend-agent: recommend-agent-system-message.txt
      booking-agent: booking-agent-system-message.txt
      consult-agent: consult-agent-system-message.txt
    memory:
      max: 100
    chat-type: ROUTE # ROUTE / ENHANCE / APP

mybatis-plus:
  type-aliases-package: com.tomorrowmust.system.domain
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: ASSIGN_ID

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

knife4j:
  enable: true
  setting:
    language: zh_cn
    swagger-model-name: 实体类列表
    enable-filter-multipart-apis: true
    enable-filter-multipart-api-method-type: POST

rocketmq:
  name-server: ${ROCKETMQ_NAMESRV:192.168.150.128:9876}
  producer:
    group: booking-producer-group

############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: satoken
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 604800
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: false
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true
  # jwt 加密密钥
  jwt-secret-key: asdasdafklhueuiwsdrfewbfjsdafjk
